### ISSUE TITLE
There is two LiveDisplay tile code and after a reboot the tile disappears from QS panel

### ISSUE THREAD

**Issue by bhb27** [ResurrectionRemix/android_frameworks_base#138]
If enable the LiveDisplay tile it works just fine, but after a reboot it is no longer in the QS panel, but if you go to settings and check in UI Tuner it is there and after the check it appears in QC panel...

Also check this...
Live display tile was remove from base in CM code in this two commit

http://review.cyanogenmod.org/#/q/topic:livedisplay-tile

As you are using UI Tuner using the CM commit to remove the base tile is not a option.

Please have a look at this when you guys have the time.

:+1:

**Comment by varund7726** [comment]
I think we have mentioned a number of times , work on M has stopped ...these issues exist in cm base for certain devices as well. 
We can't fix these issues because we won't work on them anymore.out current focus is to bring up a nice stable nougat . 
Thanks

**Comment by varund7726** [comment]
Also I am completely aware of the situation right from the start about dissapearing live display qs tile.. Its mostly because we are not using paged tiles and cmsdk to cache tile resources....unfortunately we can't fix that as we cannot focus our energy into brining back paged qs mechanism.
All you have to do to fix this a simple system UI restart .and it will be back.

**Comment by varund7726** [comment]
Oh and a small request. Please refrain from reporting bugs here..github is generally a place to report issues such as compile error or some serious problems like commits that can cause crashes , bootloops etc.
If you have minor issues , please report them on our g+ page with proper logcats .
Please refrain from posting here.
Thanks for understanding
